"""schedule added to task model

Revision ID: ac0342e33b54
Revises: fedb60613869
Create Date: 2026-01-11 10:21:32.412049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac0342e33b54'
down_revision = 'fedb60613869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule', sa.String(length=512), nullable=False, server_default="''"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('schedule')

    # ### end Alembic commands ###
