"""last checked in added to appstate

Revision ID: fedb60613869
Revises: 2bc61e6966f1
Create Date: 2026-01-11 00:00:30.746927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fedb60613869'
down_revision = '2bc61e6966f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_checked_in', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_state', schema=None) as batch_op:
        batch_op.drop_column('last_checked_in')

    # ### end Alembic commands ###
